#
# This docker-compose.dev.yml file is for development deployments of ParadeDB only. It directly builds our
# Dockerfile, which has all ParadeDB extensions pre-installed and properly configured. It is not intended for
# production use. For production usage, please use docker-compose.yml for production usage.
#
# There are several other environment variables which can be specified here to configure replication, TLS,
# and a few other settings. They can be found here:
# https://github.com/bitnami/containers/blob/main/bitnami/postgresql/README.md#environment-variables
#

services:
  paradedb-dev:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      cache_from:
        - type=local,src=./.docker_cache_dev
      cache_to:
        - type=local,dest=./.docker_cache_dev
    container_name: paradedb-dev
    environment:
      POSTGRESQL_USERNAME: myuser
      POSTGRESQL_PASSWORD: mypassword
      POSTGRESQL_DATABASE: mydatabase
      POSTGRESQL_POSTGRES_PASSWORD: postgres # Password for the superuser, required to install ParadeDB extensions
    ports:
      - "5432:5432"
